"""
Problem 2
Even Fibonacci Numbers
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

# globals
max_fib = 4000000

def even_fib():
    sum = 0
    fib1 = 1
    fib2 = 2

    while fib1 < max_fib:
        if fib1 % 2 is 0:
            sum = sum + fib1
        fib3 = fib1 + fib2
        fib1 = fib2
        fib2 = fib3

    return sum

def main():
    sum = even_fib()
    print("p002 answer:",sum)

main()
